

export const styles = (isMobile:boolean)=> ({
  container: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    paddingTop: '30px',
    paddingBottom: '30px',
    marginTop: '50px',
    borderRadius: '10px',
    maxWidth: isMobile ? '70%' : '50%',
    flexDirection: isMobile ? 'column' : 'row',
  },
  imageContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
  },
  loginAccessImg: {
    width: '100%',
    height: 'auto',
    maxWidth: '300px',
    maxHeight: '300px',
    objectFit: 'contain',
    borderRadius: '150px',
  },
  textContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    textAlign: 'center',
    paddingRight: isMobile ? '20px' : '70px',
    paddingLeft: isMobile ? '20px' : '70px',
    paddingTop: '30px',
    height: '100%',
    borderRadius: '0 10px 10px 0',
  },
  title: {
    marginBottom: '20px',
    fontSize: isMobile ? '17px' : '20px',
    color: '#666',
    fontWeight: 'bold'
  },
  description: {
    color: '#666',
    fontSize: isMobile ? '15px' : '16px',
  },
  accessLoginButton: {
    height: '50px',
    width: '170px',
    borderRadius: '10px',
    cursor: 'pointer',
    backgroundColor: '#3b87a7',
    marginTop: isMobile ? '20px' : '40px',
    marginBottom: isMobile ? '5px' : '20px',
    color: 'white',
    fontSize: isMobile ? '16px' : '18px',
    fontWeight: 'bold',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textDecoration: 'none',
    border: 'none',
    '&:hover': {
      backgroundColor: 'orange',
    },
  },
});
